services:
  consul:
    image: hashicorp/consul:1.16
    container_name: consul
    ports:
      - "8500:8500"
    command: ["agent", "-dev", "-client=0.0.0.0", "-ui"]
  catalog:
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    container_name: catalog
    depends_on: [consul]
    ports: ["55001:8080"]
  orders:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    container_name: orders
    depends_on: [consul, catalog]
    ports: ["55003:8080"]
  gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: gateway
    depends_on: [consul, catalog, orders]
    ports: ["55080:8080"]
