version: "3.9"
services:
  service_a:
    build: ./ServiceA
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    expose:
      - "8080"
  service_b:
    build: ./ServiceB
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    expose:
      - "8080"
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - service_a
      - service_b
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
