version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  vault:
    image: hashicorp/vault:1.15
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_ADDR=http://0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-listen-address=0.0.0.0:8200

  vault-init:
    image: curlimages/curl:8.7.1
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    volumes:
      - ./scripts/seed-vault.sh:/seed-vault.sh:ro
    entrypoint: ["/bin/sh","-ec"]
    command: ["sh /seed-vault.sh"]
  api:
    build: ./JwtApi
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8088
      - ConnectionStrings__Default=Server=mssql,1433;Database=JwtDemoDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - VAULT_SECRET_PATH=secret/data/jwt
    depends_on:
      mssql:
        condition: service_healthy
      vault:
        condition: service_started
      vault-init:
        condition: service_started
    ports:
      - "8088:8088"
  dbui:
    image: adminer
    depends_on:
        - mssql
    ports:
      - "28080:8080"

